<html>
<table style="width: 100%; background-color: #0C5235;color:#ffffff; border-top: 1px solid #ddd;" border="0">
<tbody>
<tr>
<td></td>
<td class="header container" style="display: block!important; max-width: 600px!important; margin: 0 auto!important; clear: both!important;">
<div style="padding: 15px; max-width: 600px; margin: 0 auto; display: block;">
<table style="width: 100%; background-color: #0C5235;" border="0">
<tbody>
<tr>
<td>
<div style="border: 1px solid #fff; padding: 5px 10px; background-color: #0C5235;color:#ffffff;">
<h3>Please Note! <small>Do not reply to this email.</small></h3>
<p style="text-align: justify;">This email was sent out by the system. If you need more assistance, please contact the phone number and email address provided below.</p>
</div>
</td>
</tr>
<tr>
<td style="text-align: left"><!--- column 2 --> 
<table style="width: 100%; float: left;" border="0">
<tbody>
<tr>
<td style="padding: 15px;color:#ffffff;" colspan="2">
<p><strong>IT Assist </strong></p>
<table style="width: 100%; color: #ffffff;" border="0">
<tbody>
<tr>
<td>Tel:</td>
<td><strong>+65 8300 6693 </strong></td>
</tr>

<tr>
<td>Email:</td>

<td><strong><a href="emailto:aungtuntun123@gmail.com" style="color: #ffffff" target="_blank">aungtuntun123@gmail.com</a></strong></td>
</tr>
<tr>
<td>Website:</td>
<td><strong><a href="web-page-url" style="color: #ffffff" target="_blank">www.renter-score.com</a></strong></td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td>
<table style="width: 100%; float: left;" border="0">
<tbody>
<tr>
<td style="padding: 15px;color: #ffffff;"><strong>Innovation Technology Pte Ltd</strong><br />
<p style="color: #ffffff">National University of Singapore</p>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</div>
</td>
 
</tr>
</tbody>
</table>
<html>