<html>
<table style="width: 100%; background-color: #0C5235;color:#ffffff; border-top: 1px solid #ddd;" border="0">
<tbody>
<tr style="background-color:#0C5235; color: #ffffff;">
<td style="" width="130" height="50">
<img src="${baseUrl}/ico.png" alt="Renter Score" style="display: block;" width="130" height="50" />
</td>
<td style="display: block; vertical-align:middle" width="70%" height="50" align="center"><h3>${title}</h3></td>
</tr>
</tbody>
</table>
</html>