name: Docker Publish

on:
  push:
      branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
     # 1. Checkout code
     - name: Checkout code
       uses: actions/checkout@v3

     # 2. Set up jdk 17
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         distribution: 'temurin'
         java-version: '17'

    # 3. Build the spring boot executable jar
     - name: Build with Gradle
       run: ./gradlew clean bootJar

    # 4. Log in to Docker Hub
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_HUB_NAME }}
         password: ${{ secrets.DOCKER_HUB_TOKEN }}

    # 5. Build the docker image
     - name: Build and push Docker image
       uses: docker/build-push-action@v3
       with:
         context: .
         push: true
         tags: ${{ secrets.DOCKER_HUB_NAME }}/spring-boot-api:latest

    # 6. Add SSH key to agent for deployment
     - name: Add SSH key
       uses: webfactory/ssh-agent@v0.5.3
       with:
         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 7. Deploy to DigitalOcean Droplet
     - name: Deploy to DigitalOcean Droplet
       run: |
         ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << 'EOF'
         docker pull ${{ secrets.DOCKER_HUB_NAME }}/react-app:latest
         docker pull ${{ secrets.DOCKER_HUB_NAME }}/spring-boot-api:latest
         docker pull ${{ secrets.DOCKER_HUB_NAME }}/dotnet-api:latest
         docker-compose up -d
         EOF
       env:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
