name: Java CI with Gradle

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests with Gradle
        run: ./gradlew test jacocoTestReport

      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-html
          path: build/reports/jacoco/test/html

      - name: Upload coverage to Codecov
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-xml
          files: build/reports/jacoco/test/jacocoTestReport.xml

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-cache
